import type { Deal } from "./types.ts";

export const SAMPLES: Deal[] = [
  {
    id: "kc-northeast",
    sample: true,
    sourceUrl: "",
    address: "4117 St. John Avenue",
    city: "Kansas City",
    state: "MO",
    zip: "64123",
    neighborhood: "Northeast",
    propertyType: "Duplex",
    strategy: "hold",
    listPrice: 152000,
    beds: 4,
    baths: 2,
    sqft: 1980,
    yearBuilt: 1924,
    lotSqft: 5200,
    taxesAnnual: 1620,
    insuranceAnnual: 1480,
    hoaMonthly: 0,
    rentMonthly: 1850,
    rehab: 6500,
    arv: 175000,
    indicatedManual: null,
    compBasis: "asis",
    priceHistory: [
      { date: "Aug 2018", price: 78500, event: "Sold" },
      { date: "May 2021", price: 125000, event: "Listed" },
      { date: "Sep 2021", price: 119000, event: "Sold" },
      { date: "Nov 2025", price: 164900, event: "Listed" },
      { date: "Feb 2026", price: 152000, event: "Price cut" },
    ],
    comps: [
      {
        address: "3920 Windsor Ave",
        status: "sold",
        price: 164000,
        date: "Jan 2026",
        beds: 4,
        baths: 2,
        sqft: 2050,
        distanceMi: 0.4,
        adjustment: -8000,
        note: "Newer mechanicals",
      },
      {
        address: "4408 St. John Ave",
        status: "sold",
        price: 148500,
        date: "Nov 2025",
        beds: 4,
        baths: 2,
        sqft: 1860,
        distanceMi: 0.2,
        adjustment: 6000,
        note: "Smaller, similar finish",
      },
      {
        address: "3716 Monroe Ave",
        status: "active",
        price: 169900,
        date: "Active",
        beds: 5,
        baths: 2,
        sqft: 2140,
        distanceMi: 0.6,
        adjustment: -12000,
        note: "Extra bedroom, higher ask",
      },
      {
        address: "4510 Bellefontaine Ave",
        status: "sold",
        price: 141000,
        date: "Dec 2025",
        beds: 4,
        baths: 1.5,
        sqft: 1720,
        distanceMi: 0.8,
        adjustment: 14000,
        note: "One less bath, smaller",
      },
    ],
    neighborhoodNotes: [
      "Northeast Kansas City trades on yield, not on a downtown appreciation story. Independence Avenue is the commercial spine; the side streets are working rentals.",
      "Duplexes here still pencil when the basis is under the mid-$150s and both units are actually occupied. Confirm the leases, not the listing’s rent claim.",
      "Street parking and alley lots are the norm. New construction is scarce, which keeps the rent ceiling local rather than luxury.",
      "Jackson County assessments move. The tax figure is last year’s bill — read the notice before you trust the cap rate.",
    ],
    riskNotes: [
      "Both units are modeled as occupied at $900 and $950. One vacancy at turnover wipes most of a year’s cash flow.",
    ],
    narrative:
      "A 1924 duplex with a February price cut, offered under the adjusted comps. This file is a yield buy if the rents are real — not a bet on the neighborhood becoming fashionable.",
  },
  {
    id: "denver-platt",
    sample: true,
    sourceUrl: "",
    address: "1846 S Grant Street",
    city: "Denver",
    state: "CO",
    zip: "80210",
    neighborhood: "Platt Park",
    propertyType: "Bungalow",
    strategy: "hold",
    listPrice: 725000,
    beds: 3,
    baths: 2,
    sqft: 1540,
    yearBuilt: 1948,
    lotSqft: 6250,
    taxesAnnual: 4200,
    insuranceAnnual: 2100,
    hoaMonthly: 0,
    rentMonthly: 2900,
    rehab: 0,
    arv: 740000,
    indicatedManual: null,
    compBasis: "asis",
    priceHistory: [
      { date: "Jun 2016", price: 485000, event: "Sold" },
      { date: "Apr 2021", price: 640000, event: "Sold" },
      { date: "Jan 2026", price: 749000, event: "Listed" },
      { date: "Mar 2026", price: 725000, event: "Price cut" },
    ],
    comps: [
      {
        address: "1688 S Pearl St",
        status: "sold",
        price: 748000,
        date: "Feb 2026",
        beds: 3,
        baths: 2,
        sqft: 1620,
        distanceMi: 0.3,
        adjustment: -18000,
        note: "Updated kitchen, larger",
      },
      {
        address: "2014 S Grant St",
        status: "sold",
        price: 710000,
        date: "Dec 2025",
        beds: 3,
        baths: 1,
        sqft: 1410,
        distanceMi: 0.4,
        adjustment: 22000,
        note: "One less bath, smaller",
      },
      {
        address: "1430 S Logan St",
        status: "active",
        price: 769000,
        date: "Active",
        beds: 3,
        baths: 2,
        sqft: 1580,
        distanceMi: 0.5,
        adjustment: -28000,
        note: "Higher finish, aspirational ask",
      },
      {
        address: "1762 S Washington St",
        status: "sold",
        price: 732000,
        date: "Jan 2026",
        beds: 3,
        baths: 2,
        sqft: 1510,
        distanceMi: 0.6,
        adjustment: 4000,
        note: "Closest match",
      },
    ],
    neighborhoodNotes: [
      "Platt Park is a primary-residence neighborhood south of Washington Park. Buyers pay for the block, the parks, and the brick, not for a cap rate.",
      "Rents never caught the 2020–2022 price move. At today’s mortgage rates this bungalow is negative leverage as a rental.",
      "The March price cut is small relative to the basis. It does not create an investment spread.",
      "Insurance on pre-war houses has stepped up. Replace the $2,100 figure with a quote before you fall in love with the payment.",
    ],
    riskNotes: [
      "Fair as a home people want. Poor as a rental. Do not let a nice block talk you into an investor’s buy box.",
    ],
    narrative:
      "A fair Platt Park bungalow after a small price cut. Comps support the ask as a place to live. They do not support it as a cash-flowing rental.",
  },
  {
    id: "indy-east",
    sample: true,
    sourceUrl: "",
    address: "1416 N Rural Street",
    city: "Indianapolis",
    state: "IN",
    zip: "46201",
    neighborhood: "Near Eastside",
    propertyType: "Single family",
    strategy: "brrrr",
    listPrice: 128000,
    beds: 3,
    baths: 1,
    sqft: 1180,
    yearBuilt: 1925,
    lotSqft: 4800,
    taxesAnnual: 1600,
    insuranceAnnual: 1200,
    hoaMonthly: 0,
    rentMonthly: 1650,
    rehab: 38000,
    arv: 215000,
    indicatedManual: null,
    compBasis: "arv",
    priceHistory: [
      { date: "Mar 2019", price: 62000, event: "Sold" },
      { date: "Oct 2024", price: 139900, event: "Listed" },
      { date: "Jan 2025", price: 139900, event: "Withdrawn" },
      { date: "Feb 2026", price: 128000, event: "Listed as-is" },
    ],
    comps: [
      {
        address: "1502 Brookside Ave",
        status: "sold",
        price: 224000,
        date: "Mar 2026",
        beds: 3,
        baths: 2,
        sqft: 1260,
        distanceMi: 0.4,
        adjustment: -9000,
        note: "Renovated, slightly larger",
      },
      {
        address: "1328 N Arsenal Ave",
        status: "sold",
        price: 208500,
        date: "Jan 2026",
        beds: 3,
        baths: 2,
        sqft: 1140,
        distanceMi: 0.7,
        adjustment: 4000,
        note: "Renovated, a bit smaller",
      },
      {
        address: "1611 E Michigan St",
        status: "active",
        price: 229000,
        date: "Active",
        beds: 3,
        baths: 2,
        sqft: 1300,
        distanceMi: 0.5,
        adjustment: -16000,
        note: "Asking above closed sales",
      },
      {
        address: "1204 N Oriental St",
        status: "sold",
        price: 211000,
        date: "Nov 2025",
        beds: 3,
        baths: 2,
        sqft: 1190,
        distanceMi: 0.6,
        adjustment: 2000,
        note: "Similar post-rehab product",
      },
    ],
    neighborhoodNotes: [
      "Near Eastside rents support renovated three-bedrooms, but the spread is earned in the rehab, not in the zip code’s reputation.",
      "These comps are renovated sales — an ARV check, not proof the as-is house is worth $215,000 today.",
      "Plan on a second bath in the $38,000 rehab. Without it, the ARV comps do not apply.",
      "Marion County reassesses after obvious renovation. The $1,600 tax bill is the as-is number.",
    ],
    riskNotes: [
      "The permanent loan at 70% of ARV barely clears. One missed month or a tax step-up and cash flow goes negative.",
      "Hard-money interest in the model is 11% for the rehab months. A slower contractor is a direct hit to cash left in the deal.",
    ],
    narrative:
      "An as-is 1925 house with a real but narrow BRRRR. The refinance returns most of the cash. It does not leave a comfortable payment.",
  },
];

export function findSample(id: string): Deal | undefined {
  return SAMPLES.find((deal) => deal.id === id);
}
