'use client'
import { useMemo, useState } from 'react'

type Book = { id:string; title:string; formula:string; fields:{id:string;label:string;step?:string}[]; calculate:(v:Record<string,number>)=>string }
const n=(v:Record<string,number>,k:string)=>Number.isFinite(v[k])?v[k]:0
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v)
const BOOKS:Book[]=[
 {id:'rehab-rent',title:'Rehab-to-rent ceiling',formula:'NOI / cap rate − rehab − closing',fields:[['rent','Monthly rent'],['opex','Operating costs %'],['cap','Target cap rate %'],['rehab','Rehab'],['closing','Closing costs']].map(([id,label])=>({id,label})),calculate:v=>n(v,'rent')>0&&n(v,'cap')>0?usd((n(v,'rent')*12*(1-n(v,'opex')/100))/(n(v,'cap')/100)-n(v,'rehab')-n(v,'closing')):'Enter rent and cap rate'},
 {id:'rehab-flip',title:'Rehab-to-flip ceiling',formula:'Resale − rehab − carry − selling costs − profit',fields:[['resale','Expected resale'],['rehab','Rehab'],['carry','Carry'],['sell','Selling costs'],['profit','Required profit']].map(([id,label])=>({id,label})),calculate:v=>usd(n(v,'resale')-n(v,'rehab')-n(v,'carry')-n(v,'sell')-n(v,'profit'))},
 {id:'land',title:'Land-flip ceiling',formula:'Resale − discount − carry − closing − survey − profit',fields:[['resale','Expected resale'],['discount','Buyer discount'],['carry','Carry'],['closing','Closing'],['survey','Survey'],['profit','Required profit']].map(([id,label])=>({id,label})),calculate:v=>usd(n(v,'resale')-n(v,'discount')-n(v,'carry')-n(v,'closing')-n(v,'survey')-n(v,'profit'))},
 {id:'long-term-rental',title:'Long-term-rental ceiling',formula:'NOI / cap rate − rehab − closing',fields:[['rent','Monthly rent'],['opex','Operating costs %'],['cap','Target cap rate %'],['rehab','Light rehab'],['closing','Closing']].map(([id,label])=>({id,label})),calculate:v=>n(v,'rent')>0&&n(v,'cap')>0?usd((n(v,'rent')*12*(1-n(v,'opex')/100))/(n(v,'cap')/100)-n(v,'rehab')-n(v,'closing')):'Enter rent and cap rate'},
 {id:'wholesale',title:'Wholesale spread',formula:'Buyer ceiling − basis − costs',fields:[['buyer','End-buyer ceiling'],['basis','Basis / seller ask'],['costs','Transaction costs']].map(([id,label])=>({id,label})),calculate:v=>usd(n(v,'buyer')-n(v,'basis')-n(v,'costs'))},
 {id:'certificate-yield',title:'Certificate simple yield',formula:'Face × rate × time; divided by capital and time',fields:[['face','Certificate face'],['rate','Winning rate %'],['months','Months held'],['subsequent','Subsequent taxes']].map(([id,label])=>({id,label})),calculate:v=>{const y=n(v,'months')/12||1;const interest=n(v,'face')*n(v,'rate')/100*y;const capital=n(v,'face')+n(v,'subsequent');return capital?`${(interest/capital/y*100).toFixed(1)}% simple annualized`: 'Enter inputs'}},
 {id:'cot-carry',title:'Certificate-of-title carry',formula:'Days × daily carry + reserve',fields:[['days','Days to title'],['daily','Daily carry'],['reserve','Objection / legal reserve']].map(([id,label])=>({id,label})),calculate:v=>usd(n(v,'days')*n(v,'daily')+n(v,'reserve'))},
 {id:'possession',title:'Cash-for-keys vs writ',formula:'Compare cash offer with filing + months of hold',fields:[['cash','Cash-for-keys offer'],['filing','Writ / filing cost'],['months','Months of hold'],['monthly','Monthly hold cost']].map(([id,label])=>({id,label})),calculate:v=>{if(n(v,'cash')<=0||n(v,'filing')<=0)return 'Enter both paths';const writ=n(v,'filing')+n(v,'months')*n(v,'monthly');return n(v,'cash')<writ?`Cash-for-keys is ${usd(writ-n(v,'cash'))} lower`: `Writ path is ${usd(n(v,'cash')-writ)} lower`}},
]
function Workbook({book}:{book:Book}){const [values,setValues]=useState<Record<string,number>>({});const result=useMemo(()=>book.calculate(values),[book,values]);return <article id={book.id} className="scroll-mt-24 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-bold text-foreground">{book.title}</h2><p className="mt-1 text-sm text-muted-foreground">{book.formula}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{book.fields.map(f=><label key={f.id} className="text-sm font-semibold text-foreground">{f.label}<input inputMode="decimal" type="number" step={f.step ?? 'any'} value={values[f.id]??''} onChange={e=>setValues({...values,[f.id]:Number(e.target.value)})} className="mt-1 min-h-11 w-full rounded-lg border border-input bg-background px-3 font-normal" /></label>)}</div><div className="mt-4 rounded-lg bg-secondary p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-primary">Educational result</p><p className="mt-1 text-xl font-bold text-foreground" aria-live="polite">{result}</p></div></article>}
export function EducationalWorkbooks(){return <><div className="not-prose my-6 grid gap-5 lg:grid-cols-2">{BOOKS.map(b=><Workbook key={b.id} book={b}/>)}</div><p className="not-prose rounded-xl border border-border bg-secondary p-4 text-sm leading-6 text-secondary-foreground"><strong>Use your own numbers.</strong> These worksheets teach deal math. They are not appraisals, bids, title opinions, legal advice, or a substitute for official records and qualified professionals.</p></>}
