import { loader } from 'fumadocs-core/source'
import { academy } from '@/.source'

/**
 * BidDeed Academy page tree (#63). `.source` is generated by the
 * `fumadocs-mdx` postinstall from source.config.ts + content/academy.
 */
export const source = loader({
  baseUrl: '/academy',
  source: academy.toFumadocsSource(),
})
