'use client'

import { FormEvent, useState } from 'react'
import PanelState from '../workspace/PanelState'

type TitleResult = { id?: string; address?: string; county?: string; case_number?: string; source?: string; source_url?: string }

export default function TitleSearchPanel() {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<TitleResult[]>([]); const [loading, setLoading] = useState(false); const [hasSearched, setHasSearched] = useState(false); const [authRequired, setAuthRequired] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  async function search(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); setNotice(null); setAuthRequired(false); setHasSearched(true); try { const response = await fetch(`/api/title-search?q=${encodeURIComponent(query.trim())}`, { credentials: 'include' }); const body = await response.json().catch(() => null); if (response.status === 401) { setAuthRequired(true); return }; if (!response.ok) throw new Error(body?.error || 'Unable to search title intelligence.'); setResults(Array.isArray(body?.results) ? body.results : []); setNotice('Results are informational and include source attribution for review.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to search title intelligence.') } finally { setLoading(false) } }
  return <section className="border border-border bg-card p-5 sm:p-6" aria-labelledby="title-search-title"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Research</p><h2 id="title-search-title" className="mt-1 text-xl font-bold text-foreground">Title intelligence</h2><p className="mt-1 text-sm text-muted-foreground">Search approved public auction and parcel fields with source attribution.</p><form onSubmit={search} className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="title-query">Address, case number, or parcel</label><input id="title-query" required value={query} onChange={(event) => setQuery(event.target.value)} className="min-h-11 flex-1 border border-input bg-background px-3 text-foreground" placeholder="Address, case number, or parcel" /><button disabled={loading} className="min-h-11 bg-primary px-4 text-sm font-bold text-primary-foreground disabled:opacity-50">{loading ? 'Searching…' : 'Search title data'}</button></form>{authRequired ? <div className="mt-4"><PanelState kind="auth" title="Sign in to search title intelligence" message="Title searches are account-scoped and logged for responsible use." actionLabel="Sign in" onAction={() => { window.location.href = '/sign-in?redirect_url=/alerts' }} /></div> : null}{error ? <div className="mt-4"><PanelState kind="error" title="Title search could not complete" message={error} actionLabel="Retry search" onAction={() => { const form = document.getElementById('title-query')?.closest('form') as HTMLFormElement | null; form?.requestSubmit() }} /></div> : null}{notice && !error ? <div className="mt-4"><PanelState kind="success" title="Title search complete" message={notice} /></div> : null}<div className="mt-5 space-y-3">{loading ? <PanelState kind="loading" title="Searching approved sources" message="Checking auction and parcel fields…" /> : null}{hasSearched && !loading && !authRequired && !error && results.length === 0 ? <PanelState kind="empty" title="No matching title data" message="Try a parcel reference, case number, or more specific address." /> : null}{results.map((result, index) => <div key={result.id || `${result.case_number}-${index}`} className="border-t border-border pt-3"><p className="font-semibold text-foreground">{result.address || result.case_number || 'Auction record'}</p><p className="text-sm text-muted-foreground">{result.county || 'County unavailable'}{result.source ? ` · Source: ${result.source}` : ''}</p>{result.source_url ? <a className="text-sm font-semibold text-primary underline-offset-4 hover:underline" href={result.source_url} target="_blank" rel="noreferrer">Open source record</a> : null}</div>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">Informational only. This is not a title opinion, legal conclusion, or substitute for professional title review.</p></section>
}
